# static analysis configuration
#
# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  errors:
    unnecessary_brace_in_string_interps: ignore # prefer consistency instead
